language: java
sudo: false
jdk:
- oraclejdk8
script:
  - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - xvfb-run mvn test -B #UI testing
  - mvn javadoc:aggregate
deploy:
  - provider: script
    skip_cleanup: true
    script: echo Deploying...
    on: 
      tags: true
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  
    keep-history: false
    local-dir: target/site
    on:
      branch: master
